# Generated by Django 5.1.1 on 2024-12-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_remove_feedback_user_feedback_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
