# Generated by Django 5.1.2 on 2025-01-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0010_rename_quantity_quantities_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='products',
        ),
        migrations.AddField(
            model_name='farmer',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
