# Generated by Django 5.1.1 on 2025-01-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0012_booking_products_productswithquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
